urdu_pos_tags = {
    "batti": "NOUN",
    "gate" : "NOUN",
    "landa": "NOUN",
    "bazar" : "NOUN",
    "gurdwaras": "NOUN",
    "makan": "NOUN",
    "jhuggees": "NOUN",
    "haveli": "NOUN",
    "madrasa": "NOUN",
    "police-thana": "NOUN",
    "paisa": "NOUN",
    "general Sahib": "NOUN",
    "zina": "NOUN",
    "raj": "NOUN",
    "tongas": "NOUN",
    "rickshaws": "NOUN",
    "ghazal": "NOUN",
    "ghazals": "NOUN",
    "izzat": "NOUN",
    "khandan": "NOUN",
    "easop-gol": "NOUN",
    "atash": "NOUN",
    "feta": "NOUN",
    "lathi": "NOUN",
    "choli": "NOUN",
    "lungi": "NOUN",
    "kurta": "NOUN",
    "dhoti": "NOUN",
    "dhotis": "NOUN",
    "kurtas": "NOUN",
    "sari": "NOUN",
    "saris": "NOUN",
    "sari-blouse": "NOUN",
    "sari-set": "NOUN",
    "palu": "NOUN",
    "shawl": "NOUN",
    "shawls": "NOUN",
    "shalwars": "NOUN",
    "shalwar-kamize": "NOUN",
    "dopattas": "NOUN",
    "kamiz": "NOUN",
    "burqas": "NOUN",
    "Kapra": "NOUN",
    "doria": "NOUN",
    "thaan": "NOUN",
    "thaans": "NOUN",
    "cummerbund": "NOUN",
    "caftan": "NOUN",
    "Bibi": "NOUN",
    "ayah": "NOUN",
    "kaki": "NOUN",
    "begum": "NOUN",
    "memsahib": "NOUN",
    "boochimai": "NOUN",
    "betiyan": "NOUN",
    "bai jee": "NOUN",
    "mai": "NOUN",
    "badmash": "NOUN",
    "guru": "NOUN",
    "lesson-walla": "NOUN",
    "Gin walla": "NOUN",
    "Jungle walla": "NOUN",
    "mujahadeen": "NOUN",
    "baba": "NOUN",
    "kaka": "NOUN",
    "mullah": "NOUN",
    "mullahs": "NOUN",
    "maulvi": "NOUN",
    "sufi": "NOUN",
    "sher": "NOUN",
    "yaar": "NOUN",
    "sala": "NOUN",
    "heejras": "NOUN",
    "afeemi": "NOUN",
    "goonda": "NOUN",
    "goondas": "NOUN",
    "haramzada": "NOUN",
    "pathan": "NOUN",
    "paindoo": "NOUN",
    "Kalay Khan": "NOUN",
    "lahori Parsees": "NOUN",
    "nawabs": "NOUN",
    "gujrati": "NOUN",
    "qawals": "NOUN",
    "punjabi": "NOUN",
    "Data Sahib": "NOUN",
    "Pakis": "ADJ",
    "gora": "ADJ",
    "Kashmiri": "ADJ",
    "pakoras": "NOUN",
    "roti": "NOUN",
    "paans": "NOUN",
    "pora": "NOUN",
    "dal": "NOUN",
    "whiskypani": "NOUN",
    "chutney": "NOUN",
    "gup-shup": "NOUN",
    "anjuman": "NOUN",
    "anjumans": "NOUN",
    "mushairas": "NOUN",
    "mehfil": "NOUN",
    "bandarosti prayer": "NOUN",
    "khutba": "NOUN",
    "kusti": "NOUN",
    "panchayat": "NOUN",
    "quawali": "NOUN",
    "khoos-poosing": "VERB",
    "salaamed": "VERB",
    "salaaming": "ADJ",
    "salaam": "NOUN",
    "Choop kar": "VERB",
    "bus kar": "VERB",
    "ghoor ghoor ke": "VERB",
    "desi": "NOUN",
    "desis": "NOUN",
    "khaki": "NOUN",
    "khush": "NOUN",
    "khandani": "NOUN",
    "basmati": "NOUN",
    "fakir like": "ADJ",
    "caftaned": "ADJ",
    "mullahish": "ADJ",
    "badshahi": "ADJ",
    "chitta": "ADJ",
    "gora chitta": "ADJ",
    "pajamaed": "ADJ",
    "tanchoi": "ADJ",
    "cashmere": "ADJ",
    "banarsi": "ADJ",
    "acha": "NOUN",
}
