urdu_pos_tags = {
    "batti gate": "NOUN",
    "Landa Bazar": "NOUN",
    "gurdwaras": "NOUN",
    "makan": "NOUN",
    "jhuggees": "NOUN",
    "haveli": "NOUN",
    "madrasa": "ADJ",
    "police-thana": "ADJ",
    "paisa": "VERB",
    "General Sahib": "VERB",
    "Zina": "NOUN",
    "Raj": "NOUN",
    "tongas": "NOUN",
    "rickshaws": "NOUN",
    "ghazal": "NOUN",
    "ghazals": "NOUN",
    "izzat": "NOUN",
    "khandan": "NOUN",
    "easop-gol": "NOUN",
    "atash": "NOUN",
    "feta": "NOUN",
    "lathi": "NOUN",
    "choli": "NOUN",
    "lungi": "NOUN",
    "kurta": "NOUN",
    "dhoti": "NOUN",
    "dhotis": "NOUN",
    "kurtas": "NOUN",
    "sari": "NOUN",
    "saris": "NOUN",
    "sari-blouse": "NOUN",
    "sari-set": "NOUN",
    "palu": "NOUN",
    "shawl": "NOUN",
    "shawls": "NOUN",
    "shalwars": "NOUN",
    "shalwar-kamize": "NOUN",
    "dopattas": "NOUN",
    "Kamiz": "NOUN",
    "burqas": "NOUN",
    "Kapra": "NOUN",
    "doria": "NOUN",
    "thaan": "NOUN",
    "thaans": "NOUN",
    "cummerbund": "NOUN",
    "caftan": "NOUN",
    "Bibi": "NOUN",
    "ayah": "NOUN",
    "kaki": "NOUN",
    "begum": "NOUN",
    "memsahib": "NOUN",
    "boochimai": "NOUN",
    "betiyan": "NOUN",
    "bai jee": "NOUN",
    "mai": "NOUN",
    "badmash": "NOUN",
    "guru": "NOUN",
    "lesson-walla": "NOUN",
    "Gin walla": "NOUN",
    "Jungle walla": "NOUN",
    "Mujahadeen": "NOUN",
    "baba": "NOUN",
    "kaka": "NOUN",
    "mullah": "NOUN",
    "mullahs": "NOUN",
    "maulvi": "NOUN",
    "sufi": "NOUN",
    "sher": "NOUN",
    "yaar": "NOUN",
    "Sala": "NOUN",
    "heejras": "NOUN",
    "afeemi": "NOUN",
    "goonda": "NOUN",
    "goondas": "NOUN",
    "haramzada": "NOUN",
    "pathan": "NOUN",
    "paindoo": "NOUN",
    "Kalay Khan": "NOUN",
    "Lahori Parsees": "NOUN",
    "nawabs": "NOUN",
    "gujrati": "NOUN",
    "qawals": "NOUN",
    "Punjabi": "NOUN",
    "Data Sahib": "NOUN",
    "Pakis": "NOUN",
    "gora": "NOUN",
    "Kashmiri": "NOUN",
    "pakoras": "NOUN",
    "Roti": "NOUN",
    "paans": "NOUN",
    "pora": "NOUN",
    "dal": "NOUN",
    "whiskypani": "NOUN",
    "chutney": "NOUN",
    "gup-shup": "NOUN",
    "Anjuman": "NOUN",
    "anjumans": "NOUN",
    "mushairas": "NOUN",
    "mehfil": "NOUN",
    "Tandarosti prayer": "NOUN",
    "khutba": "NOUN",
    "kusti": "NOUN",
    "panchayat": "NOUN",
    "quawali": "NOUN",
    "khoos-poosing": "NOUN",
    "salaamed": "NOUN",
    "salaaming": "NOUN",
    "salaam": "NOUN",
    "Choop kar": "NOUN",
    "bus kar": "NOUN",
    "ghoor ghoor ke": "NOUN",
    "desi": "NOUN",
    "desis": "NOUN",
    "khaki": "NOUN",
    "khush": "NOUN",
    "khandani": "NOUN",
    "Basmati": "NOUN",
    "fakir like": "NOUN",
    "caftaned": "NOUN",
    "mullahish": "NOUN",
    "Badshahi": "NOUN",
    "chitta": "NOUN",
    "gora chitta": "NOUN",
    "pajamaed": "NOUN",
    "tanchoi": "NOUN",
    "cashmere": "NOUN",
    "banarsi": "NOUN",
    "kashmiri": "NOUN",
}
